meta_product_name: "SANLIFE"
meta_title: "SANLIFE - find out which foods are best for you"
meta_description: "We generate a list of foods containing the nutrients that you need."
meta_image: "cover.png" # should exist in `app/assets/images/`
